const num = `
<table class="tabela1" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 1</td>
        </tr>
        <tr>
        <tr>
            <td>1x1</td>
            <td>1</td>
        </tr>
        </tr>
        <tr>
            <td>1x2</td>
            <td>2</td>
        </tr>
        <tr>
            <td>1x3</td>
            <td>3</td>
        </tr>
        <tr>
            <td>1x4</td>
            <td>4</td>
        </tr>
        <tr>
            <td>1x5</td>
            <td>5</td>
        </tr>
        <tr>
            <td>1x6</td>
            <td>6</td>
        </tr>
        <tr>
            <td>1x7</td>
            <td>7</td>
        </tr>
        <tr>
            <td>1x8</td>
            <td>8</td>
        </tr>
        <tr>
            <td>1x9</td>
            <td>9</td>
        </tr>
        <tr>
            <td>1x10</td>
            <td>10</td>
        </tr>

    </thead>
</table>
<table class="tabela2" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 2</td>
        </tr>
        <tr>
        <tr>
            <td>2x1</td>
            <td>2</td>
        </tr>
        </tr>
        <tr>
            <td>2x2</td>
            <td>4</td>
        </tr>
        <tr>
            <td>2x3</td>
            <td>6</td>
        </tr>
        <tr>
            <td>2x4</td>
            <td>8</td>
        </tr>
        <tr>
            <td>2x5</td>
            <td>10</td>
        </tr>
        <tr>
            <td>2x6</td>
            <td>12</td>
        </tr>
        <tr>
            <td>2x7</td>
            <td>14</td>
        </tr>
        <tr>
            <td>2x8</td>
            <td>16</td>
        </tr>
        <tr>
            <td>2x9</td>
            <td>18</td>
        </tr>
        <tr>
            <td>2x10</td>
            <td>20</td>
        </tr>

    </thead>
</table>
<table class="tabela3" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 3</td>
        </tr>
        <tr>
        <tr>
            <td>3x1</td>
            <td>3</td>
        </tr>
        </tr>
        <tr>
            <td>3x2</td>
            <td>6</td>
        </tr>
        <tr>
            <td>3x3</td>
            <td>9</td>
        </tr>
        <tr>
            <td>3x4</td>
            <td>12</td>
        </tr>
        <tr>
            <td>3x5</td>
            <td>15</td>
        </tr>
        <tr>
            <td>3x6</td>
            <td>18</td>
        </tr>
        <tr>
            <td>3x7</td>
            <td>21</td>
        </tr>
        <tr>
            <td>3x8</td>
            <td>24</td>
        </tr>
        <tr>
            <td>3x9</td>
            <td>227</td>
        </tr>
        <tr>
            <td>3x10</td>
            <td>30</td>
        </tr>

    </thead>
</table>
<table class="tabela4" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 4</td>
        </tr>
        <tr>
        <tr>
            <td>4x1</td>
            <td>4</td>
        </tr>
        </tr>
        <tr>
            <td>4x2</td>
            <td>8</td>
        </tr>
        <tr>
            <td>4x3</td>
            <td>12</td>
        </tr>
        <tr>
            <td>4x4</td>
            <td>16</td>
        </tr>
        <tr>
            <td>4x5</td>
            <td>20</td>
        </tr>
        <tr>
            <td>4x6</td>
            <td>24</td>
        </tr>
        <tr>
            <td>4x7</td>
            <td>28</td>
        </tr>
        <tr>
            <td>4x8</td>
            <td>32</td>
        </tr>
        <tr>
            <td>4x9</td>
            <td>36</td>
        </tr>
        <tr>
            <td>4x10</td>
            <td>40</td>
        </tr>

    </thead>
</table>
<table class="tabela5" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 5</td>
        </tr>
        <tr>
        <tr>
            <td>5x1</td>
            <td>5</td>
        </tr>
        </tr>
        <tr>
            <td>5x2</td>
            <td>10</td>
        </tr>
        <tr>
            <td>5x3</td>
            <td>15</td>
        </tr>
        <tr>
            <td>5x4</td>
            <td>20</td>
        </tr>
        <tr>
            <td>5x5</td>
            <td>25</td>
        </tr>
        <tr>
            <td>5x6</td>
            <td>30</td>
        </tr>
        <tr>
            <td>5x7</td>
            <td>35</td>
        </tr>
        <tr>
            <td>5x8</td>
            <td>40</td>
        </tr>
        <tr>
            <td>5x9</td>
            <td>45</td>
        </tr>
        <tr>
            <td>5x10</td>
            <td>50</td>
        </tr>

    </thead>
</table>
<table class="tabela6" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 6</td>
        </tr>
        <tr>
        <tr>
            <td>6x1</td>
            <td>6</td>
        </tr>
        </tr>
        <tr>
            <td>6x2</td>
            <td>12</td>
        </tr>
        <tr>
            <td>6x3</td>
            <td>18</td>
        </tr>
        <tr>
            <td>6x4</td>
            <td>24</td>
        </tr>
        <tr>
            <td>6x5</td>
            <td>30</td>
        </tr>
        <tr>
            <td>6x6</td>
            <td>36</td>
        </tr>
        <tr>
            <td>6x7</td>
            <td>42</td>
        </tr>
        <tr>
            <td>6x8</td>
            <td>48</td>
        </tr>
        <tr>
            <td>6x9</td>
            <td>545</td>
        </tr>
        <tr>
            <td>6x10</td>
            <td>60</td>
        </tr>

    </thead>
</table>
<table class="tabela7" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 7</td>
        </tr>
        <tr>
        <tr>
            <td>7x1</td>
            <td>7</td>
        </tr>
        </tr>
        <tr>
            <td>7x2</td>
            <td>14</td>
        </tr>
        <tr>
            <td>7x3</td>
            <td>21</td>
        </tr>
        <tr>
            <td>7x4</td>
            <td>28</td>
        </tr>
        <tr>
            <td>7x5</td>
            <td>35</td>
        </tr>
        <tr>
            <td>7x6</td>
            <td>42</td>
        </tr>
        <tr>
            <td>7x7</td>
            <td>49</td>
        </tr>
        <tr>
            <td>7x8</td>
            <td>56</td>
        </tr>
        <tr>
            <td>7x9</td>
            <td>63</td>
        </tr>
        <tr>
            <td>7x10</td>
            <td>70</td>
        </tr>

    </thead>
</table>
<table class="tabela8" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 8</td>
        </tr>
        <tr>
        <tr>
            <td>8x1</td>
            <td>8</td>
        </tr>
        </tr>
        <tr>
            <td>8x2</td>
            <td>16</td>
        </tr>
        <tr>
            <td>8x3</td>
            <td>24</td>
        </tr>
        <tr>
            <td>8x4</td>
            <td>32</td>
        </tr>
        <tr>
            <td>8x5</td>
            <td>40</td>
        </tr>
        <tr>
            <td>8x6</td>
            <td>48</td>
        </tr>
        <tr>
            <td>8x7</td>
            <td>56</td>
        </tr>
        <tr>
            <td>8x8</td>
            <td>64</td>
        </tr>
        <tr>
            <td>8x9</td>
            <td>72</td>
        </tr>
        <tr>
            <td>8x10</td>
            <td>80</td>
        </tr>

    </thead>
</table>
<table class="tabela9" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 9</td>
        </tr>
        <tr>
        <tr>
            <td>9x1</td>
            <td>9</td>
        </tr>
        </tr>
        <tr>
            <td>9x2</td>
            <td>18</td>
        </tr>
        <tr>
            <td>9x3</td>
            <td>27</td>
        </tr>
        <tr>
            <td>9x4</td>
            <td>36</td>
        </tr>
        <tr>
            <td>9x5</td>
            <td>45</td>
        </tr>
        <tr>
            <td>9x6</td>
            <td>54</td>
        </tr>
        <tr>
            <td>9x7</td>
            <td>63</td>
        </tr>
        <tr>
            <td>9x8</td>
            <td>72</td>
        </tr>
        <tr>
            <td>9x9</td>
            <td>81</td>
        </tr>
        <tr>
            <td>9x10</td>
            <td>90</td>
        </tr>

    </thead>
</table>
<table class="tabela10" id="tableMy">
    <thead>
        <tr>
            <td class="Produto1" colspan=2>Produto de 10</td>
        </tr>
        <tr>
        <tr>
            <td>10x1</td>
            <td>10</td>
        </tr>
        </tr>
        <tr>
            <td>10x2</td>
            <td>20</td>
        </tr>
        <tr>
            <td>10x3</td>
            <td>30</td>
        </tr>
        <tr>
            <td>10x4</td>
            <td>40</td>
        </tr>
        <tr>
            <td>10x5</td>
            <td>50</td>
        </tr>
        <tr>
            <td>10x6</td>
            <td>60</td>
        </tr>
        <tr>
            <td>10x7</td>
            <td>70</td>
        </tr>
        <tr>
            <td>10x8</td>
            <td>80</td>
        </tr>
        <tr>
            <td>10x9</td>
            <td>90</td>
        </tr>
        <tr>
            <td>10x10</td>
            <td>100</td>
        </tr>

    </thead>
</table>

`
// function criaTabela()
// {
//     const body = document.body, tbl = document.createElement('table');

//     for (let i = 1; i <= 10; i++) {
//         const tr = tbl.insertRow();
//         for (let j = 1; j <= 10; j++) {
//             const td = tr.insertCell();
//             td.appendChild(document.createTextNode(`${i} x ${j} = ${i*j}`));
//         }
        
//     }
//     body.appendChild(tbl);
// }
document.writeln(num)
//criaTabela();
